# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 12:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_project',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_voter',
        ),
        migrations.RemoveField(
            model_name='creativity',
            name='creativity_project',
        ),
        migrations.RemoveField(
            model_name='creativity',
            name='creativity_voter',
        ),
        migrations.RemoveField(
            model_name='usability',
            name='usability_voter',
        ),
        migrations.RemoveField(
            model_name='usability',
            name='userbility_project',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='design_voter',
            new_name='voter',
        ),
        migrations.AddField(
            model_name='design',
            name='contentvote',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='design',
            name='creativityvote',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='design',
            name='usabilityvote',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Creativity',
        ),
        migrations.DeleteModel(
            name='Usability',
        ),
    ]
